### ISSUE TITLE
lua support

### ISSUE THREAD

**Issue by carlwgeorge** [iuscommunity-pkg/haproxy16u#1]
Now that we have [lua53u](iuscommunity/wishlist#15), we _could_ enable the USE_LUA flag on this package to enable lua support.  Does anyone want this and is willing to test?

**Comment by carlwgeorge** [comment]
This has been added in the [haproxy16u-1.6.11-2 build](https://github.com/iuscommunity-pkg/haproxy16u/releases/tag/1.6.11-2).

@Fale Did you get a chance to test it?

**Comment by Fale** [comment]
Sorry not yet. I'll try to do it tomorrow

**Comment by b-harper** [comment]
We went ahead and released packages with lua support.  If anyone runs into issues, please open a new issue.
